#The sequence of triangle numbers is generated by adding the natural numbers. So the $7$<sup>th</sup> triangle number would be $1 + 2 + 3 + 4 + 5 + 6 + 7 = 28$. The first ten terms would be:
#1, 3, 6, 10, 15, 21, 28, 36, 45, 55, \dots$$</p>
#Let us list the factors of the first seven triangle numbers:</p>
#\mathbf 1 &amp;\colon 1\\
#\mathbf 3 &amp;\colon 1,3\\
#\mathbf 6 &amp;\colon 1,2,3,6\\
#\mathbf{10} &amp;\colon 1,2,5,10\\
#\mathbf{15} &amp;\colon 1,3,5,15\\
#\mathbf{21} &amp;\colon 1,3,7,21\\
#\mathbf{28} &amp;\colon 1,2,4,7,14,28
#We can see that $28$ is the first triangle number to have over five divisors.
#What is the value of the first triangle number to have over five hundred divisors?

from sympy import divisors

nDivisors=500
i = 1
while True:
    #trick for triangle numbers
    n = sum(range(1,i+1))
    i += 1
    if(len(divisors(n)) > nDivisors):
        print(n, len(divisors(n)))
        break



	
